server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/e_commerce
spring.datasource.username=postgres
spring.datasource.password=2007nura

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
